### ISSUE TITLE
US 1 Accessible Room List for Teachers 

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#1]
## Value Proposition

As a teacher, I want to be able to view a list of rooms 
in order to get an overview of the available rooms.
​

## Description

A montessori school needs a way to manage the school's rooms. Every day, students have a two-hour window to study independently on a subject of their choice. They can select a room where they want to study, but each room has a limited availability of seats. With over 500 students simultaneously looking for a free room, the lack of knowledge about seat availability often results in chaos. In this user story, the initial aim is to create the possibility for teachers to have an overview of all the rooms in the school.

![Bildschirmfoto 2023-07-19 um 13 06 55](https://github.com/ekat-br/roomcheck/assets/64787391/9cda25e7-22ac-4e18-9349-247383124197)

​

## Acceptance Criteria

- [x] The list of all rooms should be easily accessible and prominently displayed within the app.
- [x] The list should include all rooms from the rooms array.
- [x] There should be a title called 'RoomCheck'

      
## Tasks
- [x] Create a new branch called 'us1-roomlist'
- [x] Create a RoomList component with an array to store the room names (only includes room names and an id)
- [x] Create dummy data for the rooms array (starting with 5 room examples) 
- [x] Retrieve the room data from the array and display each room list element by using the map method 
- [x] Change the title of the Header Component to 'RoomCheck'

**Comment by actyvystom** [comment]
A great and impressive first one! 🚀 
A nice and well formed value proposition, clear acceptance criteria 👍🏻  
Concerning your development tasks, you should add more technical detail, _e.g. design a visually user interface for the room list(...)_ and _Apply responsive design principles(...)_ could be a pitfall... And you should also add where to retrieve the room data from (is it static dummy data first? what structure? etc.)
It is always good practice to add the creating of a branch and its name as a task, just to avoid forgetting it in times of capstone stress ;)

**Comment by ekat-br** [comment]
@actyvystom Thank you for the feedback. I applied the suggested changes.

**Comment by Roland-Hufnagel** [comment]
Hi Katja, really a great job right now. But I saw one other point: Since this is your starting point and you don't have other pages at this moment you don't need a navigation with a home button. This does not make any sense for the user at this time. So you should put the navigation to a later coming userstory (when you define a second page and want to switch between them).

**Comment by ekat-br** [comment]
Thank you Roland, I totally understand your point. I applied the changes.

**Comment by actyvystom** [comment]
LGTM 🚀

**Comment by mrrubinello** [comment]
ja geht so...
