### ISSUE TITLE
US6 Teacher - Student View

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#11]
## Value Proposition

As a teacher, I want to be able to manage the room states in order to keep the availability information up-to-date. 
As a student, I want to be able to read the room states in order to know which rooms are available.
​

## Description
The app should display different views based on the user role. Teachers should have the ability to manage the room states, allowing them to update the current availability of the rooms. On the other hand, students should only have read access to the room states, enabling them to view the availability information without the ability to make changes. The implementation will be done using routing without a login system initially.

![Bildschirmfoto 2023-07-24 um 14 26 33](https://github.com/ekat-br/roomcheck/assets/64787391/6d23162f-6bbc-433b-9b04-f7e1e6125218)

## Acceptance Criteria

- [ ] For teachers accessing the room list, buttons displaying the states "Keine Angabe," "Plätze frei," "Wenige Plätze frei," and "Plätze belegt" should be visible and editable. 
- [ ] When a teacher updates the room states, the changes should be saved in the database.
- [ ] For students accessing the room list, buttons displaying the current room states should be visible, but not editable.
- [ ] The views for teachers and students should be different based on their respective user roles, without the need for a login system.​
     
## Tasks

- [x] Create a new branch called 'us6-teacher-student-view'.
- [x] Set up specific routing for teachers and students based on their user roles.
- [x] Ensure that the room list page displays the appropriate view with the state buttons for teachers and read-only buttons for students.

**Comment by Bilal4317** [comment]
very detailed nice
