### ISSUE TITLE
US7 Create new Rooms

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#13]
## Value Proposition

As an admin, I want to be able to create new rooms in order to expand the available room options. 
​

## Description
Currently, the app has a fixed set of rooms and there is a need to add new rooms. To achieve this, the admin role should have the functionality to create new rooms and make them available in the room list.

![Bildschirmfoto 2023-07-25 um 12 11 04](https://github.com/ekat-br/roomcheck/assets/64787391/ded29c3c-3aeb-4e6f-8d56-f1fbee02856a)
​

## Acceptance Criteria

- [ ] The admin should have access to a dedicated "Create Room" page or form with appropriate routing (e.g., pages/admin/index.js).
- [ ] The "Create Room" form should include necessary input elements for the admin to enter room details, such as room name and subject.
- [ ] The form should have a submit button to allow the admin to create the new room.
- [ ] Upon successful submission of the form, a new room should be created and added to the list of available rooms.
- [ ] The app should provide a navigation option for the admin role, allowing the admin to switch between the "Homepage" and the "Create Room Page." The navigation should include a home icon to return to the homepage and a plus icon to navigate to the "Create Room Page."
      ​

## Tasks

- [x] Create a new branch called 'us7-create-new-rooms'.
- [x] Set up specific routing for admin (pages/admin/index.js).
- [x] Create a component RoomForm and render a form with a title, two input elements, labels and a submit button
- [x] Implement backend API routes to handle the creation of new rooms and store them in the database.
- [x] create a function to handle the Form submission 
- [x] Connect the frontend component with the backend API to create new rooms.
- [x] Create a navigation for the admin role to switch between Homepage and 'Create Room Page" with a home icon and an plus icon

**Comment by Bilal4317** [comment]
cool description. lgtm
