### ISSUE TITLE
US9 Delete Rooms

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#15]
## Value Proposition

As an admin,
I want to be able to delete rooms
so that I can remove unnecessary or no longer available rooms from the app and keep the room list updated.
​

## Description

Currently, the app allows admins to manage the room list by adding new rooms. However, there is also a need to remove rooms that are no longer required or available. To achieve this, the admin role should have the functionality to delete existing rooms from the room list.

![Bildschirmfoto 2023-07-26 um 10 23 11](https://github.com/ekat-br/roomcheck/assets/64787391/36a39a5e-2f06-48b9-bd7a-2612a66ac4c9)

​

## Acceptance Criteria

 - [ ] The admin should have the ability to delete a room from the room list.
 - [ ] The room should be removed from the list of available rooms and deleted from the database.
 - [ ] After successful deletion, the room list should be updated to reflect the changes.
 

## Tasks

 - [ ] Create a new branch called 'us8-delete-rooms'.
 - [ ] Implement backend API routes to handle the deletion of rooms from the database.
 - [ ] Create a delete button
 - [ ] Create a function to handle the room deletion action in the frontend.
 - [ ] Connect the frontend component with the backend API to perform the room deletion.
 - [ ] Update the room list after successful deletion to reflect the changes.

**Comment by Roland-Hufnagel** [comment]
Perfect US 💪
