### ISSUE TITLE
US 2 Create room button with a default state

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#2]
## Value Proposition
​
As a teacher, 
I want to be able to view the default state for all rooms 
in order to check the current status of the rooms.

## Description

By providing teachers with the ability to view the default seat availability for all rooms, they can quickly assess the current status of each room. This empowers them to make decisions and efficiently search for available rooms during the independent study period. In this user story, only the button for each list element is to be built with a default value.

![Image](https://github.com/ekat-br/roomcheck/assets/64787391/8b519218-7d43-4077-a90d-7254bb08700e)

## Acceptance Criteria

- [x] there should be displayed a button for each room list element
- [x] the button should be placed inside of the list element
- [x] the button should look the same for each list element
- [x] the button should be displayed with the default text 'Keine Angabe'
      ​

## Tasks

- [x] create a new branch called us2-roombuttondefault
- [x] create a RoomButton Component 
- [x] render the room button for each list element
- [x] display the button inside of each list element
- [x] store the default value for the button inside of the rooms array (state: 'Keine Angabe')
- [x] build the functionality to display the default value for each room retrieved from the rooms array
