### ISSUE TITLE
US11 Login for Admin

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#24]
## Value Proposition

As an Admin
I want to be able to log in
so that I can access the admin room list and manage rooms with administrative privileges.
​

## Description

As an admin user, I want to have the ability to log in to the application using my GitHub account. Once logged in, I should be able to access the admin room list, which displays all the rooms in the application with administrative privileges. From the admin room list, I can perform various administrative tasks such as creating, updating and deleting rooms. 

<img width="528" alt="Bildschirmfoto 2023-08-03 um 15 13 33" src="https://github.com/ekat-br/roomcheck/assets/64787391/852beed4-a3c6-4164-8313-bbecfa315c31">

## Acceptance Criteria

- [ ] The login feature should use GitHub OAuth for authentication.
- [ ] When clicking the "Log in with GitHub" button, the user should be redirected to the GitHub login page.
- [ ] After successful GitHub authentication, the user should be redirected back to the application and logged in as an admin.
- [ ] If the user is not an admin or does not have the necessary permissions, they should see an error message
- [ ] Admin users should have the ability to create new rooms using a "Create Room" button, which navigates to a room creation form.
- [ ] Admin users should have the ability to update room details by clicking an "Edit" button next to each room in the list, which navigates to a room edit form.
- [ ] Admin users should have the ability to delete rooms using a "Delete" button next to each room in the list.
- [ ] A Navigation with a HomeButton and a LoginButton is displayed
      ​

## Tasks

- [ ]  create branch `us11-login`
- [ ] Install NextAuth.js and required dependencies (npm install next-auth).
- [ ] Create a configuration file for NextAuth.js and configure GitHub as the authentication provider.
- [ ] Generate GitHub OAuth credentials for the application and store them securely.
- [ ] Create the [...nextauth].js file inside the pages/api folder with the appropriate GitHub configuration.
- [ ] Set up environment variables (.env.local file) to store the GitHub OAuth credentials securely.
- [ ] Create a login component (components/Login.js) with a "Log in with GitHub" button.
- [ ] Implement the authentication flow using NextAuth.js to allow admin users to log in via GitHub.
- [ ] Implement logic to check if the logged-in user is an admin with the necessary permissions.
- [ ] Redirect the user to the admin room list upon successful login and authentication.
- [ ] Add a Navigation with HomeButton and LoginButton to switch between different pages

**Comment by StrongCurrent** [comment]
All glories to the mighty and holy user story 😁. LGMT - Rock on and good luck
