### ISSUE TITLE
US12 Login for Teacher

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#26]
## Value Proposition

As a teacher, 
I want to log in to the app 
in order to manage room statuses.

## Description

<img width="380" alt="Bildschirmfoto 2023-08-04 um 15 18 01" src="https://github.com/ekat-br/roomcheck/assets/64787391/e05c24fd-b6f9-446c-b1dd-0e98e52c4609">

​

## Acceptance Criteria

- [ ] Teachers with the role "teacher" should be allowed to log in, and others should be denied access.
- [ ] Upon successful login, the teacher should be redirected to the teacher page.
      ​

## Tasks

- [ ] Create branch "teacher-login"
- [ ] Set up the NextAuth.js configuration with the "Credentials" provider for teacher login.
- [ ] Implement redirection to the teacher page upon successful login.
