### ISSUE TITLE
US13 School Design

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#28]
## Value Proposition

As a user
I want to see the app designed with the school theme
in order to create a familiar experience that aligns with the context of the educational environment.

## Description

<img width="698" alt="Bildschirmfoto 2023-08-08 um 10 28 35" src="https://github.com/ekat-br/roomcheck/assets/64787391/80064125-7ac9-47c2-b7e8-62cdab7f246c">

​

## Acceptance Criteria

- [ ] Changed theme
      ​

## Tasks

- [x] create branch 'styling'
- [x] Change Divider
- [x] Change Navigation - Icon color
- [x] Change Button Color
- [x] Add Logo 
- [x] Change Heading
