### ISSUE TITLE
US 3 Display room status based on array entry

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#3]
## Value Proposition

As a teacher, 
I want to see the current availability status of each room, 
in order to quickly check the overall availability of seats.
​

## Description

By being able to view the current status of the room based on the rooms array entry, teachers can accurately assess the availability of the room. 

![Bildschirmfoto 2023-07-19 um 13 16 36](https://github.com/ekat-br/roomcheck/assets/64787391/b50beb06-0d38-4f44-81ba-b34d442f4e3d)

​

## Acceptance Criteria

- [x] The buttons have following texts: 'Keine Angabe' or 'Plätze frei' or 'Wenige Plätze frei' or 'Plätze belegt'
- [x] The buttons have the desired colors based on the text: grey for 'Keine Angabe', green for 'Plätze frei', orange for 'Wenige Plätze frei' and red for 'Plätze belegt'
      ​

## Tasks

- [x] create a new branch called 'us3-roomstatus'
- [x] extend the rooms array with dummy data for the room status 
- [x] build a functionality to display the button with text based on the rooms array entry 
- [x] Select corresponding colors for the buttons that ensure good contrast and accessibility.
- [x] build a functionality to display the button color based on the corresponding status text from the rooms array entry

**Comment by HannesOster** [comment]
Hey Katja,
In the value proposition there is the word "array" used which is maybe a little unneccessary technical

**Comment by ekat-br** [comment]
Hey Johannes, thanks for your feedback. I changed the value proposition.
