### ISSUE TITLE
US 4  Toggle Functionality for Room State Button 

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#4]
## Value Proposition 

As a teacher,
I want to be able to modify the state of a room, 
so that I can keep the information about the room up to date.
​

## Description

By having the ability to modify the state of a room, teachers can ensure that the information about the room is accurate and up to date. This allows them to manage the room effectively and provide reliable information to students and other users.

![Bildschirmfoto 2023-07-19 um 14 15 03](https://github.com/ekat-br/roomcheck/assets/64787391/7340eabd-5caf-48e8-b8fd-aa3240df3dbf)

## Acceptance Criteria

- [x] All buttons can be toggled between all four states: "Keine Angabe" (no information provided), "Plätze frei" (seats available), "Wenige Plätze frei" (few seats available), and "Plätze belegt" (seats occupied).
- [x] The buttons still have the desired colors based on the text: grey for 'Keine Angabe', green for 'Plätze frei', orange for 'Wenige Plätze frei' and red for 'Plätze belegt'
      ​

## Tasks

- [x] Create a new branch called 'us4-toggle-button'
- [x] Implement the toggle functionality for the button, allowing it to be toggled between different states. 
- [x] Update the state of the room in the rooms array when the button is toggled.
