### ISSUE TITLE
US 5 Setup Database

### ISSUE THREAD

**Issue by ekat-br** [ekat-br/roomcheck#9]
## Value Proposition
​
As a teacher, 
I want the room information to be stored in a database,
so that the data is persistent and can be easily managed.

## Description

Currently, room information is stored in an array within the application. However, this approach has limitations, as there is no easy way to manage the room information. To overcome these limitation, the room information should be stored in a database, allowing for better data management.

![Bildschirmfoto 2023-07-23 um 22 06 51](https://github.com/ekat-br/roomcheck/assets/64787391/f857d613-05cc-42c1-ba94-59df698a7920)

## Acceptance Criteria

All functionalities from the previous user stories should continue to work seamlessly with the new database setup:

- [ ] The list of all rooms should be easily accessible and prominently displayed within the app.
- [ ] The buttons have following texts: 'Keine Angabe' or 'Plätze frei' or 'Wenige Plätze frei' or 'Plätze belegt'
- [ ] The buttons have the desired colors based on the text: grey for 'Keine Angabe', green for 'Plätze frei', orange for 'Wenige Plätze frei' and red for 'Plätze belegt'
- [ ] All buttons can be toggled between all four states: "Keine Angabe" (no information provided), "Plätze frei" (seats available), "Wenige Plätze frei" (few seats available), and "Plätze belegt" (seats occupied)
- [ ] When toggling the buttons still have the desired colors based on the text: grey for 'Keine Angabe', green for 'Plätze frei', orange for 'Wenige Plätze frei' and red for 'Plätze belegt'
      ​

## Tasks

- [x] Create a new branch called 'us5-database-connection'.
- [x] Set up a database (MongoDB) to store room information.
- [x] Design a database schema to represent room data, including fields for room names, availability status and subject. 
- [x] Implement backend API routes to handle database operations for rooms (read room list, update room status)
- [x] Set up the backend server to establish a connection with the MongoDB database. 
- [x] Modify the RoomList component to fetch room information from the database. Replace the previous array-based data with API calls to retrieve room data from the backend.
- [x] Implement the functionality in the RoomButton component to interact with the database. When toggling the room status, the RoomButton component should make the necessary API call to update the room status in the database.

**Comment by StrongCurrent** [comment]
This is a beautiful user story. Good luck with your implementation.
